/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hiberus.hotels.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Hotel service. Represents a row in the &quot;HOTELS_Hotel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.hiberus.hotels.model.impl.HotelModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.hiberus.hotels.model.impl.HotelImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Hotel
 * @generated
 */
@ProviderType
public interface HotelModel
	extends BaseModel<Hotel>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a hotel model instance should use the {@link Hotel} interface instead.
	 */

	/**
	 * Returns the primary key of this hotel.
	 *
	 * @return the primary key of this hotel
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this hotel.
	 *
	 * @param primaryKey the primary key of this hotel
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this hotel.
	 *
	 * @return the uuid of this hotel
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this hotel.
	 *
	 * @param uuid the uuid of this hotel
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the hotel ID of this hotel.
	 *
	 * @return the hotel ID of this hotel
	 */
	public long getHotelId();

	/**
	 * Sets the hotel ID of this hotel.
	 *
	 * @param hotelId the hotel ID of this hotel
	 */
	public void setHotelId(long hotelId);

	/**
	 * Returns the group ID of this hotel.
	 *
	 * @return the group ID of this hotel
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this hotel.
	 *
	 * @param groupId the group ID of this hotel
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this hotel.
	 *
	 * @return the company ID of this hotel
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this hotel.
	 *
	 * @param companyId the company ID of this hotel
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this hotel.
	 *
	 * @return the user ID of this hotel
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this hotel.
	 *
	 * @param userId the user ID of this hotel
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this hotel.
	 *
	 * @return the user uuid of this hotel
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this hotel.
	 *
	 * @param userUuid the user uuid of this hotel
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this hotel.
	 *
	 * @return the user name of this hotel
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this hotel.
	 *
	 * @param userName the user name of this hotel
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this hotel.
	 *
	 * @return the create date of this hotel
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this hotel.
	 *
	 * @param createDate the create date of this hotel
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this hotel.
	 *
	 * @return the modified date of this hotel
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this hotel.
	 *
	 * @param modifiedDate the modified date of this hotel
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this hotel.
	 *
	 * @return the name of this hotel
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this hotel.
	 *
	 * @param name the name of this hotel
	 */
	public void setName(String name);

	/**
	 * Returns the email of this hotel.
	 *
	 * @return the email of this hotel
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this hotel.
	 *
	 * @param email the email of this hotel
	 */
	public void setEmail(String email);

	/**
	 * Returns the address of this hotel.
	 *
	 * @return the address of this hotel
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this hotel.
	 *
	 * @param address the address of this hotel
	 */
	public void setAddress(String address);

	/**
	 * Returns the location of this hotel.
	 *
	 * @return the location of this hotel
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this hotel.
	 *
	 * @param location the location of this hotel
	 */
	public void setLocation(String location);

	/**
	 * Returns the foundation date of this hotel.
	 *
	 * @return the foundation date of this hotel
	 */
	public Date getFoundationDate();

	/**
	 * Sets the foundation date of this hotel.
	 *
	 * @param foundationDate the foundation date of this hotel
	 */
	public void setFoundationDate(Date foundationDate);

	@Override
	public Hotel cloneWithOriginalValues();

}