/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hiberus.hotels.model.impl;

import com.hiberus.hotels.model.Room;
import com.hiberus.hotels.model.RoomModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Room service. Represents a row in the &quot;HOTELS_Room&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>RoomModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RoomImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RoomImpl
 * @generated
 */
@JSON(strict = true)
public class RoomModelImpl extends BaseModelImpl<Room> implements RoomModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a room model instance should use the <code>Room</code> interface instead.
	 */
	public static final String TABLE_NAME = "HOTELS_Room";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"roomId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"hotelId", Types.BIGINT}, {"number_", Types.INTEGER},
		{"type_", Types.VARCHAR}, {"size_", Types.INTEGER},
		{"price", Types.DOUBLE}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("roomId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("hotelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("number_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("size_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("price", Types.DOUBLE);
	}

	public static final String TABLE_SQL_CREATE =
		"create table HOTELS_Room (uuid_ VARCHAR(75) null,roomId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,hotelId LONG,number_ INTEGER,type_ VARCHAR(75) null,size_ INTEGER,price DOUBLE)";

	public static final String TABLE_SQL_DROP = "drop table HOTELS_Room";

	public static final String ORDER_BY_JPQL =
		" ORDER BY room.hotelId ASC, room.number ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY HOTELS_Room.hotelId ASC, HOTELS_Room.number_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long HOTELID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TYPE_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NUMBER_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public RoomModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _roomId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setRoomId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _roomId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Room.class;
	}

	@Override
	public String getModelClassName() {
		return Room.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Room, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Room, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Room, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Room)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Room, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Room, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Room)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Room, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Room, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Room, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Room, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Room, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Room, Object>>();
		Map<String, BiConsumer<Room, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Room, ?>>();

		attributeGetterFunctions.put("uuid", Room::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Room, String>)Room::setUuid);
		attributeGetterFunctions.put("roomId", Room::getRoomId);
		attributeSetterBiConsumers.put(
			"roomId", (BiConsumer<Room, Long>)Room::setRoomId);
		attributeGetterFunctions.put("groupId", Room::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Room, Long>)Room::setGroupId);
		attributeGetterFunctions.put("companyId", Room::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Room, Long>)Room::setCompanyId);
		attributeGetterFunctions.put("userId", Room::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Room, Long>)Room::setUserId);
		attributeGetterFunctions.put("userName", Room::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Room, String>)Room::setUserName);
		attributeGetterFunctions.put("createDate", Room::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Room, Date>)Room::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Room::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate", (BiConsumer<Room, Date>)Room::setModifiedDate);
		attributeGetterFunctions.put("hotelId", Room::getHotelId);
		attributeSetterBiConsumers.put(
			"hotelId", (BiConsumer<Room, Long>)Room::setHotelId);
		attributeGetterFunctions.put("number", Room::getNumber);
		attributeSetterBiConsumers.put(
			"number", (BiConsumer<Room, Integer>)Room::setNumber);
		attributeGetterFunctions.put("type", Room::getType);
		attributeSetterBiConsumers.put(
			"type", (BiConsumer<Room, String>)Room::setType);
		attributeGetterFunctions.put("size", Room::getSize);
		attributeSetterBiConsumers.put(
			"size", (BiConsumer<Room, Integer>)Room::setSize);
		attributeGetterFunctions.put("price", Room::getPrice);
		attributeSetterBiConsumers.put(
			"price", (BiConsumer<Room, Double>)Room::setPrice);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getRoomId() {
		return _roomId;
	}

	@Override
	public void setRoomId(long roomId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_roomId = roomId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getHotelId() {
		return _hotelId;
	}

	@Override
	public void setHotelId(long hotelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_hotelId = hotelId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalHotelId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("hotelId"));
	}

	@JSON
	@Override
	public int getNumber() {
		return _number;
	}

	@Override
	public void setNumber(int number) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_number = number;
	}

	@JSON
	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalType() {
		return getColumnOriginalValue("type_");
	}

	@JSON
	@Override
	public int getSize() {
		return _size;
	}

	@Override
	public void setSize(int size) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_size = size;
	}

	@JSON
	@Override
	public double getPrice() {
		return _price;
	}

	@Override
	public void setPrice(double price) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_price = price;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Room.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Room.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Room toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Room>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RoomImpl roomImpl = new RoomImpl();

		roomImpl.setUuid(getUuid());
		roomImpl.setRoomId(getRoomId());
		roomImpl.setGroupId(getGroupId());
		roomImpl.setCompanyId(getCompanyId());
		roomImpl.setUserId(getUserId());
		roomImpl.setUserName(getUserName());
		roomImpl.setCreateDate(getCreateDate());
		roomImpl.setModifiedDate(getModifiedDate());
		roomImpl.setHotelId(getHotelId());
		roomImpl.setNumber(getNumber());
		roomImpl.setType(getType());
		roomImpl.setSize(getSize());
		roomImpl.setPrice(getPrice());

		roomImpl.resetOriginalValues();

		return roomImpl;
	}

	@Override
	public Room cloneWithOriginalValues() {
		RoomImpl roomImpl = new RoomImpl();

		roomImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		roomImpl.setRoomId(this.<Long>getColumnOriginalValue("roomId"));
		roomImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		roomImpl.setCompanyId(this.<Long>getColumnOriginalValue("companyId"));
		roomImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		roomImpl.setUserName(this.<String>getColumnOriginalValue("userName"));
		roomImpl.setCreateDate(this.<Date>getColumnOriginalValue("createDate"));
		roomImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		roomImpl.setHotelId(this.<Long>getColumnOriginalValue("hotelId"));
		roomImpl.setNumber(this.<Integer>getColumnOriginalValue("number_"));
		roomImpl.setType(this.<String>getColumnOriginalValue("type_"));
		roomImpl.setSize(this.<Integer>getColumnOriginalValue("size_"));
		roomImpl.setPrice(this.<Double>getColumnOriginalValue("price"));

		return roomImpl;
	}

	@Override
	public int compareTo(Room room) {
		int value = 0;

		if (getHotelId() < room.getHotelId()) {
			value = -1;
		}
		else if (getHotelId() > room.getHotelId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		if (getNumber() < room.getNumber()) {
			value = -1;
		}
		else if (getNumber() > room.getNumber()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Room)) {
			return false;
		}

		Room room = (Room)object;

		long primaryKey = room.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Room> toCacheModel() {
		RoomCacheModel roomCacheModel = new RoomCacheModel();

		roomCacheModel.uuid = getUuid();

		String uuid = roomCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			roomCacheModel.uuid = null;
		}

		roomCacheModel.roomId = getRoomId();

		roomCacheModel.groupId = getGroupId();

		roomCacheModel.companyId = getCompanyId();

		roomCacheModel.userId = getUserId();

		roomCacheModel.userName = getUserName();

		String userName = roomCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			roomCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			roomCacheModel.createDate = createDate.getTime();
		}
		else {
			roomCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			roomCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			roomCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		roomCacheModel.hotelId = getHotelId();

		roomCacheModel.number = getNumber();

		roomCacheModel.type = getType();

		String type = roomCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			roomCacheModel.type = null;
		}

		roomCacheModel.size = getSize();

		roomCacheModel.price = getPrice();

		return roomCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Room, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Room, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Room, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Room)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Room>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Room.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _roomId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _hotelId;
	private int _number;
	private String _type;
	private int _size;
	private double _price;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Room, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Room)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("roomId", _roomId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("hotelId", _hotelId);
		_columnOriginalValues.put("number_", _number);
		_columnOriginalValues.put("type_", _type);
		_columnOriginalValues.put("size_", _size);
		_columnOriginalValues.put("price", _price);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("number_", "number");
		attributeNames.put("type_", "type");
		attributeNames.put("size_", "size");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("roomId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("hotelId", 256L);

		columnBitmasks.put("number_", 512L);

		columnBitmasks.put("type_", 1024L);

		columnBitmasks.put("size_", 2048L);

		columnBitmasks.put("price", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Room _escapedModel;

}